Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  puts "Enter the number of virtual machines (from 1 to 253): "
  vm_count = Integer(STDIN.gets)

  unless (1..253).include?(vm_count)
    puts "The number of VMs is incorrect. Please enter a number from 1 to 253."
    exit
  end

  config.vm.box = "generic/ubuntu1804"

  (1..vm_count).each do |i|
    config.vm.define "vm#{i}" do |vm|
      vm.vm.box = "generic/ubuntu1804"
      vm.vm.hostname = "avoevoda-vm#{i}"
      vm.vm.network "private_network", ip: "192.168.55.#{i + 10}"
      vm.vm.provider "virtualbox" do |vb|
        vb.name = "avoevoda-vm#{i}"
      end
    end
  end
end