Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

 # VM 1
  config.vm.define "vm1" do |vm1|
  vm1.vm.box = "generic/ubuntu1804"
  vm1.vm.hostname = "avoevoda-vm1"
  vm1.vm.network "private_network", ip: "192.168.55.10"

  vm1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y git
      git config --global user.name "avoevoda433"
      git config --global user.email "avoevoda433@gmail.com"
      git clone https://github.com/avoevoda433/Vagrant_lab1
      cat Vagrant_lab1/task2/module2.txt
    SHELL
 end

 # VM 2
  config.vm.define "vm2" do |vm2|
  vm2.vm.box = "generic/ubuntu1804"
  vm2.vm.hostname = "vm2"
  vm2.vm.network "private_network", ip: "192.168.55.20"
 end
end